async page=>{
 const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));const ok=(name,pass)=>{checks.push({name,pass});if(!pass)throw Error(name);};
 await page.setViewportSize({width:1440,height:900});await page.goto('http://127.0.0.1:8765/presentation/?revision=interaction1');await page.waitForFunction(()=>window.__careRover);
 const seek=t=>page.evaluate(t=>__careRover.seek(t),t),snap=()=>page.evaluate(()=>__careRover.snapshot());
 for(const [start,part] of [[18,'camera'],[38,'ultrasonic']]){await seek(start);ok('Sensor chapter starts as whole robot '+part,Object.values((await snap()).interaction.reveal).every(v=>v===1));await seek(start+1);let r=(await snap()).interaction.reveal;ok('Continuous transparency during reveal '+part,r.shell>0.08&&r.shell<1&&r[part]===1);await seek(start+4);r=(await snap()).interaction.reveal;ok('Focus keeps translucent installation context '+part,r.shell>0&&r.shell<.1&&r[part]===1);const a=await page.locator('#stage canvas').screenshot();await seek(109);await seek(start+4);ok('Reverse seek reproduces sculpted sensor frame '+part,a.equals(await page.locator('#stage canvas').screenshot()));await page.screenshot({path:`output/playwright/v7/interaction-${part}.png`});await seek(start+9);ok('Whole robot returns before next chapter '+part,(await snap()).interaction.reveal.shell>.4);}
 for(const [t,label] of [[69,'TWO'],[74,'DISLIKE'],[79,'LIKE']]){await seek(t);ok('3D gesture '+label,(await snap()).interaction.gesture===label&&(await snap()).interaction.visible);ok('No flat card '+label,await page.locator('#gestureCard').isHidden());await page.screenshot({path:`output/playwright/v7/interaction-${label}.png`});}
 await seek(76.5);ok('Neutral interval clears hand',!(await snap()).interaction.visible);await seek(22);await page.evaluate(()=>__careRover.enterInspect());await page.waitForTimeout(100);ok('Inspect resets transparency',Object.values((await snap()).interaction.reveal).every(v=>v===1));
 await page.evaluate(()=>__careRover.leaveInspect());await page.setViewportSize({width:390,height:844});for(const t of [22,42,69]){await seek(t);await page.screenshot({path:`output/playwright/v7/interaction-mobile-${t}.png`});ok('Mobile no horizontal overflow '+t,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 ok('No browser errors',errors.length===0);return {total:checks.length,checks,errors};
}
