async page => {
  const results=[],check=(name,value,detail)=>{if(!value)throw Error(name+': '+JSON.stringify(detail));results.push({name,status:'PASS',detail});};
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript({path:'tests/browser/v6_ws_fixture.js'});
  let streamRequests=0;page.on('request',r=>{if(r.url().includes('8767/stream'))streamRequests++;});
  await page.setViewportSize({width:1440,height:1000});await page.goto('http://127.0.0.1:8765/?transport=ws');
  await page.waitForFunction(()=>v6Fixture.seq>3);
  check('passive page neither opens the single-viewer stream nor claims control',streamRequests===0&&await page.evaluate(()=>v6Fixture.messages.every(m=>m.type==='ping')));
  check('gesture entry is device-native, no mandatory gesture-mode button',await page.locator('[data-mode="GESTURE_CONTROL"]').count()===0);
  await page.evaluate(()=>{v6Fixture.mode='PERSON_FOLLOW';v6Fixture.owned=false;dispatchEvent(new Event('blur'));});await page.waitForTimeout(180);
  check('passive blur does not cancel independent gesture follow',await page.evaluate(()=>v6Fixture.mode==='PERSON_FOLLOW'&&!v6Fixture.messages.some(m=>m.type==='cmd_vel')));
  await page.locator('[data-mode="MANUAL"]').click();await page.waitForTimeout(120);await page.keyboard.down('w');await page.waitForTimeout(180);await page.keyboard.up('w');await page.waitForTimeout(100);
  check('manual input sends nonzero motion and scoped release',await page.evaluate(()=>v6Fixture.messages.some(m=>m.type==='cmd_vel'&&m.vx>0)&&v6Fixture.messages.some(m=>m.type==='cmd_vel'&&m.release_only&&!m.vx)));
  await page.evaluate(()=>{v6Fixture.mode='GESTURE_CONTROL';v6Fixture.owned=v6Fixture.occupied=false;});await page.waitForTimeout(400);
  check('delayed page release cannot cancel subsequent autonomous gesture',await page.evaluate(()=>v6Fixture.mode==='GESTURE_CONTROL'));
  await page.locator('#btnStop').click();await page.waitForTimeout(140);
  check('explicit Stop still sends a normal zero to cancel autonomous action',await page.evaluate(()=>v6Fixture.mode==='IDLE'&&v6Fixture.messages.some(m=>m.type==='cmd_vel'&&!m.release_only&&!m.vx&&!m.vy&&!m.wz)));
  await page.locator('#videoSourceSel').selectOption('mjpeg');await page.waitForFunction(()=>document.querySelector('#videoStage').dataset.videoStatus==='live'&&document.querySelector('#frameState').textContent==='新帧接收中');
  check('real multipart JPEG fixture is decoded and reported as fresh',await page.locator('#frameState').textContent()==='新帧接收中');
  await page.screenshot({path:'output/playwright/v6/console-stream.png'});
  await page.evaluate(()=>{v6Fixture.action={seq:1,label:'TWO',accepted:false,reason:'CONTROL_BUSY',age_ms:0};});await page.waitForTimeout(180);
  check('recognized gesture does not masquerade as action acceptance',(await page.locator('#actionTitle').textContent()).includes('未启动'));
  await page.evaluate(()=>{v6Fixture.stream='http://127.0.0.1:8767/stream?scenario=freeze';});
  await page.waitForFunction(()=>document.querySelector('#videoStage').dataset.videoStatus==='stale'&&document.querySelector('#frameState').textContent==='暂无新帧',{},{timeout:6000});
  check('video freeze is reported while robot telemetry continues',await page.evaluate(async()=>{const s=await import('/js/state.js');return !s.isRobotStale()&&document.querySelector('#frameState').textContent==='暂无新帧'&&!document.querySelector('#videoError').hidden;}));
  await page.screenshot({path:'output/playwright/v6/console-video-stale.png'});
  await page.evaluate(()=>{v6Fixture.stream='http://127.0.0.1:8767/stream?scenario=busy';});await page.waitForFunction(()=>document.querySelector('#videoStage').dataset.videoStatus==='busy');
  const beforeBusy=streamRequests;await page.waitForTimeout(1200);check('single-viewer busy is explained with manual retry, no reconnect loop',streamRequests===beforeBusy&&(await page.locator('#videoError').textContent()).includes('占用'));
  await page.locator('#estopBtn').click();await page.waitForTimeout(200);check('fresh robot-specific emergency confirmation is shown',(await page.locator('#sessionTitle').textContent()).includes('设备已上报'));
  await page.evaluate(()=>{v6Fixture.robot=false;});await page.waitForTimeout(1650);
  check('C03 health and IMU traffic cannot keep robot emergency confirmation fresh',!(await page.locator('#sessionTitle').textContent()).includes('设备已上报')&&await page.evaluate(async()=>{const s=await import('/js/state.js');return !s.isTelemetryStale()&&s.isRobotStale();}));
  check('C03 stale robot mode and target are unknown',await page.locator('#sMode').textContent()==='—'&&await page.locator('#sVel').textContent()==='—');
  await page.screenshot({path:'output/playwright/v6/console-partial-telemetry.png'});
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:'output/playwright/v6/console-mobile.png',fullPage:true});
  check('390px console has no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  check('primary controls retain at least 44px targets',await page.evaluate(()=>['estopBtn','btnStop','rotL','rotR','videoSourceSel','langToggle'].every(id=>document.getElementById(id).getBoundingClientRect().height>=44)));
  await page.setViewportSize({width:1440,height:900});
  check('no uncaught browser exception',errors.length===0,errors);return results;
}
