import * as T from 'three';
import {OrbitControls} from '../vendor/three/examples/jsm/controls/OrbitControls.js';
import {loadRobot} from '../scene/robot.js';
import {makeAssembly,openingAt} from './assembly.js';
import {lightProduct} from './lighting.js';
import {makeScan,makeEcho} from './effects.js';
const $=id=>document.getElementById(id),query=new URLSearchParams(location.search),exporting=query.has('export');document.body.dataset.export=exporting;
const shots={structure:{title:['每一层，','都有秩序。'],eyebrow:'DESIGNED FROM WITHIN',description:'打开机身。\n看见细节之间的联系。',note:'装配关系示意 · 退出路径待实物安装核对',eye:[-.49,.30,.55],target:[.004,.125,0]},scan:{title:['看见。','然后理解。'],eyebrow:'A DIFFERENT WAY TO SEE',description:'光掠过表面。\n让感知，有迹可循。',note:'感知可视化 · 摄像头不发射可见激光',eye:[-.185,.136,.230],target:[-.092,.066,0]},echo:{title:['距离，','有了回响。'],eyebrow:'EVERY RETURN TELLS A STORY',description:'一次发出。一次回应。\n在向前之前，知道距离。',note:'声波原理示意 · 传播已放慢，非实测声束',eye:[-.195,.158,.275],target:[-.098,.092,0]}};
let shot='structure',time=0,playing=false,direction=1,last=0,view='hero',dirty=true,lost=false;
const scene=new T.Scene(),camera=new T.PerspectiveCamera(30,1,.001,4),renderer=new T.WebGLRenderer({alpha:true,antialias:true,preserveDrawingBuffer:exporting});renderer.setPixelRatio(exporting?1:Math.min(devicePixelRatio,1.75));renderer.setClearColor(0,0);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;$('stage').append(renderer.domElement);lightProduct(scene,renderer);
const controls=new OrbitControls(camera,renderer.domElement);controls.enablePan=false;controls.enableDamping=false;controls.minDistance=.12;controls.maxDistance=1.4;controls.addEventListener('change',()=>dirty=true);controls.addEventListener('start',()=>{playing=false;sync();});
let robot,assembly,scan,echo,lastEvent={};
function sync(){document.body.dataset.shot=shot;$('scrub').value=time;$('clock').value=`${time.toFixed(1).padStart(4,'0')} / 10`;$('play').textContent=playing?'Ⅱ':'▷';$('play').setAttribute('aria-label',playing?'暂停':'播放');}
function setCamera(){const s=shots[shot],eye=new T.Vector3(...s.eye),target=new T.Vector3(...s.target);if(shot==='structure'&&view!=='hero'){const r=.72;if(view==='front')eye.copy(target).add(new T.Vector3(-r,.07,0));if(view==='side')eye.copy(target).add(new T.Vector3(0,.08,r));if(view==='top')eye.copy(target).add(new T.Vector3(-.001,r,.001));}eye.sub(target).multiplyScalar(Math.max(1,1.4/camera.aspect)).add(target);camera.position.copy(eye);controls.target.copy(target);camera.lookAt(target);}
function choose(id){shot=id;time=0;last=0;playing=false;view='hero';const s=shots[id];$('title').replaceChildren(document.createTextNode(s.title[0]),document.createElement('br'));const span=document.createElement('span');span.textContent=s.title[1];$('title').append(span);$('eyebrow').textContent=s.eyebrow;$('description').textContent=s.description;$('note').textContent=s.note;$('views').hidden=id!=='structure';document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.view==='hero'));document.querySelectorAll('[data-shot]').forEach(b=>{if(b.tagName==='BUTTON')b.setAttribute('aria-pressed',b.dataset.shot===shot);});controls.enabled=!exporting;setCamera();sync();dirty=true;}
function pose(){assembly.apply(shot==='structure'?openingAt(time):0);scan.root.visible=echo.root.visible=false;robot.root.position.set(0,0,0);robot.root.rotation.set(0,0,0);if(shot!=='structure')for(const i of robot.instances)i.node.visible=i.id===(shot==='scan'?'camera':'ultrasonic');robot.root.updateMatrixWorld(true);
 if(shot==='scan')lastEvent=scan.update(time);else if(shot==='echo')lastEvent=echo.update(time);else lastEvent={phase:time<.8?'完整装配':time<4.4?'依次展开':time<5.6?'层层关联':time<9.2?'回到完整':'完整装配',open:openingAt(time)};
 $('phase').textContent=lastEvent.phase;sync();}
function resize(){const r=$('stage').getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();setCamera();dirty=true;}
function frame(now){requestAnimationFrame(frame);if(!robot||lost||document.hidden){last=0;return;}if(playing){if(last)time=Math.max(0,Math.min(10,time+(now-last)/1000*direction));if((direction>0&&time>=10)||(direction<0&&time<=0))playing=false;dirty=true;}last=now;if(dirty){pose();renderer.render(scene,camera);dirty=false;}}
async function boot(){try{robot=await loadRobot();scene.add(robot.root);assembly=makeAssembly(robot);assembly.apply(0);scan=makeScan(robot.effects.camera.anchor);echo=makeEcho(robot.effects.ultrasonic.anchor);robot.materials.white.roughness=.56;robot.materials.white.color.set('#d9dddf');robot.materials.silver.roughness=.25;robot.materials.rubber.color.set('#14171a');$('loading').hidden=true;choose(query.get('shot') in shots?query.get('shot'):'structure');resize();pose();renderer.render(scene,camera);
 window.__v7={choose,seek:async(t)=>{playing=false;time=Math.max(0,Math.min(10,t));pose();renderer.render(scene,camera);await new Promise(requestAnimationFrame);return lastEvent;},view:v=>{view=v;setCamera();dirty=true;},snapshot:()=>({shot,time,event:lastEvent,objects:robot.instances.map(i=>({id:i.node.name,position:i.node.position.toArray(),quaternion:i.node.quaternion.toArray(),visible:i.node.visible,box:(()=>{const b=new T.Box3().setFromObject(i.appearance);const projected=[];for(const x of [b.min.x,b.max.x])for(const y of [b.min.y,b.max.y])for(const z of [b.min.z,b.max.z])projected.push(new T.Vector3(x,y,z).project(camera).toArray());return {min:b.min.toArray(),max:b.max.toArray(),projected};})()})),hit:echo.hit.toArray(),camera:camera.position.toArray(),target:controls.target.toArray(),calls:renderer.info.render.calls})};requestAnimationFrame(frame);
 }catch(e){$('loading').textContent='样片暂时无法加载。请刷新后重试。';console.error(e);}}
document.querySelectorAll('button[data-shot]').forEach(b=>b.onclick=()=>choose(b.dataset.shot));document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;setCamera();document.querySelectorAll('[data-view]').forEach(v=>v.setAttribute('aria-pressed',v===b));dirty=true;});$('play').onclick=()=>{direction=1;if(time>=10)time=0;playing=!playing;last=0;sync();};$('watch').onclick=()=>{time=0;direction=1;playing=true;last=0;dirty=true;sync();};$('reverse').onclick=()=>{direction=-1;if(time<=0)time=10;playing=true;last=0;sync();};$('scrub').oninput=e=>{playing=false;time=Number(e.target.value);dirty=true;};$('fullscreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen().catch(()=>{});};window.addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>last=0);renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();lost=true;playing=false;$('loading').hidden=false;$('loading').textContent='3D 已暂停。刷新页面可重新查看样片。';});boot();
