import test from 'node:test';import assert from 'node:assert/strict';
import {evaluate,DURATION,Director,scenes,independentMotion,careEvent,gestureEvent} from '../presentation/v7/director.js';
test('V7 chapter coverage has no gaps, deterministic reverse seek and finite camera',()=>{assert.equal(scenes[0].start,0);assert.equal(scenes.at(-1).end,DURATION);scenes.slice(1).forEach((s,i)=>assert.equal(s.start,scenes[i].end));for(let t=0;t<=DURATION;t+=.25){const a=evaluate(t);evaluate(DURATION-t);assert.deepEqual(evaluate(t),a);assert.ok([...a.eye,...a.target].every(Number.isFinite));assert.ok(a.open>=0&&a.open<=1);}});
test('all assembly stages close to exact rest on same timeline',()=>{assert.equal(evaluate(5).open,0);assert.equal(evaluate(12).open,1);assert.equal(evaluate(18).open,0);assert.equal(evaluate(112).open,0);});
test('motion retains lateral orientation and accumulated whole revolution',()=>{assert.equal(independentMotion(8).yaw,0);assert.ok(independentMotion(8).position[2]<0);assert.equal(independentMotion(17).yaw,-2*Math.PI);assert.deepEqual(independentMotion(17),independentMotion(18));});
test('gesture confirms before executing and has neutral interval',()=>{assert.equal(gestureEvent(57).accepted,false);assert.equal(gestureEvent(59).label,'TWO');assert.equal(gestureEvent(64).label,'DISLIKE');assert.equal(gestureEvent(66.5).label,'NONE');assert.equal(gestureEvent(69).label,'LIKE');});
test('hand event and OLED cannot show result outside contact',()=>{for(let t=80;t<96;t+=.1){const e=careEvent(t),s=evaluate(t);if(!e.contact){assert.equal(e.hr,null);assert.equal(e.spo2,null);assert.equal(s.oled.line2,'NO FINGER');}if(e.hr){assert.equal(s.oled.line2,'72 BPM  98%');assert.ok(e.contact);}}});
test('Deck holds chapter end; Film resets its time reference after pause',()=>{const d=new Director();d.setMode('deck');d.chapter(2);d.tick(0);d.tick(200);assert.equal(d.time,scenes[2].end);assert.equal(d.playing,false);d.setMode('film');d.play();d.tick(900);assert.equal(d.time,38);d.tick(901);assert.equal(d.time,39);});

// The approved 10-second study is retained verbatim at film seconds 7..17.
import {openingAt,structureShot,advanceAssembly,ease} from '../presentation/v7/structure.js';
test('opening and closing retain the approved study clock and fixed camera',()=>{for(let t=0;t<=10;t+=.05){const s=evaluate(7+t);assert.ok(Math.abs(s.open-openingAt(t))<1e-12);assert.deepEqual(s.eye,structureShot(16/9).eye);assert.deepEqual(s.target,structureShot(16/9).target);}});
test('Inspect travels the same 3.6-second path and reverses without snapping',()=>{let phase=0;for(let i=0;i<108;i++){phase=advanceAssembly(phase,1,1/30);assert.ok(Math.abs(ease(phase)-openingAt(.8+(i+1)/30))<1e-12);}assert.ok(Math.abs(phase-1)<1e-12);for(let i=0;i<108;i++)phase=advanceAssembly(phase,0,1/30);assert.ok(phase<1e-12);const mid=advanceAssembly(.5,0,1/30);assert.ok(mid<.5&&mid>.49);assert.equal(advanceAssembly(0,0,5),0);assert.equal(advanceAssembly(1,1,5),1);});

import {faceFollow} from '../presentation/v7/director.js';
test('Face tracking follows independent target with lag then settles, no extra slide',()=>{assert.equal(scenes.length,9);assert.ok(!scenes.some(s=>s.id==='follow'));assert.equal(evaluate(36).chapter,'vision');assert.equal(evaluate(38).chapter,'range');for(const t of [28,29,30,31,32,33,34,35,36,37]){const f=faceFollow(t);assert.equal(evaluate(t).pose.position[2],f.robotZ);assert.ok(Math.abs(f.targetZ)<=.0420001);}assert.ok(faceFollow(29).targetZ>faceFollow(29).robotZ);assert.ok(faceFollow(33).targetZ<faceFollow(33).robotZ);assert.ok(Math.abs(faceFollow(37.8).robotZ)<1e-9);});
