#!/usr/bin/env python3
"""Deterministic browser frame capture + H.264 export. Uses the production director.
Start: python3 -m http.server 8765; playwright-cli --session v6-film open http://127.0.0.1:8765/presentation/?export=1
Requires npx, Playwright CLI, and imageio-ffmpeg. Captures 150 s at 1920x1080/30 fps.
"""
import argparse,subprocess,json,time,hashlib,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
p=argparse.ArgumentParser();p.add_argument('--session',default='v6-film');p.add_argument('--start',type=int,default=0);p.add_argument('--end',type=int,default=4500);p.add_argument('--encode-only',action='store_true');a=p.parse_args()
frames=ROOT/'build/film-frames';frames.mkdir(parents=True,exist_ok=True)
logs=ROOT/'build/film-capture.log'
def source_hashes():
 return {p.relative_to(ROOT).as_posix():hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted((ROOT/'presentation').rglob('*')) if p.is_file() and p.name!='manifest.json' and 'film' not in p.parts and p.suffix in {'.js','.html','.css','.glb','.json','.jpg','.png'}}
source_hash=source_hashes()
cli=['npx','--yes','--package','@playwright/cli@0.1.20','playwright-cli','--session',a.session,'run-code']
def run(code):
 r=subprocess.run(cli+[code],cwd=ROOT,text=True,capture_output=True)
 with logs.open('a') as f:f.write(r.stdout+r.stderr+'\n')
 if r.returncode or '### Error' in r.stdout:raise RuntimeError(r.stdout+r.stderr)
if not a.encode_only:
 run("async page=>{await page.setViewportSize({width:1920,height:1080});await page.goto('http://127.0.0.1:8765/presentation/?export=1');await page.waitForFunction(()=>window.__careRover);return {ready:true};}")
 for start in range(a.start,a.end,90):
  end=min(a.end,start+90);began=time.monotonic()
  run(f'''async page=>{{for(let i={start};i<{end};i++){{await page.evaluate(t=>window.__careRover.seek(t),i/30);await page.screenshot({{path:`build/film-frames/${{String(i).padStart(5,'0')}}.jpg`,type:'jpeg',quality:95}});}}return {{start:{start},end:{end}}};}}''')
  print(f'Captured {end}/4500 ({time.monotonic()-began:.1f}s per batch)',flush=True)
if source_hashes()!=source_hash:raise RuntimeError('Presentation source/assets changed during capture')
if a.end!=4500:raise SystemExit(0)
missing=[i for i in range(4500) if not (frames/f'{i:05d}.jpg').is_file()]
if missing:raise RuntimeError(f'Missing {len(missing)} frames, first {missing[:4]}')
import imageio_ffmpeg
out=ROOT/'presentation/assets/film';out.mkdir(exist_ok=True)
args=[imageio_ffmpeg.get_ffmpeg_exe(),'-y','-framerate','30','-i',str(frames/'%05d.jpg'),'-i',str(ROOT/'build/film-score.wav'),'-t','150','-c:v','libx264','-preset','slow','-crf','21','-pix_fmt','yuv420p','-c:a','aac','-b:a','160k','-movflags','+faststart',str(out/'CareRover-film.mp4')]
r=subprocess.run(args,capture_output=True,text=True);(ROOT/'build/film-encode.log').write_text(r.stderr);r.check_returncode()
shutil.copyfile(frames/'00090.jpg',out/'poster.jpg')
meta={'durationSeconds':150,'width':1920,'height':1080,'fps':30,'frames':4500,'source':'production presentation/story/director.js and scene modules','simulation':True,'renderSourceHashes':source_hash,'audio':'Original procedural ambient score generated by tools/film_score.py; no samples','files':{}}
for name in ['CareRover-film.mp4','poster.jpg','console-demo.mp4']:
 data=(out/name).read_bytes();meta['files'][name]={'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest()}
(out/'FILM_MANIFEST.json').write_text(json.dumps(meta,ensure_ascii=False,indent=2)+'\n');print(json.dumps(meta,ensure_ascii=False),flush=True)
